; Global variables
Global $global_sock

; This gets generated by SDL2 in the menu and has a trailing slash.
; The menu sends this as soon, as the meta component connects.
Global $global_config_path = NULL

Global $global_game_instances_open = 0
Global $global_game_process_ids[6]


; Initialize Arrayss
For $i=0 To 5
	$global_game_process_ids[$i] = 0
Next

; Zero-terminated string reply to the server
Func re($message)
	TCPSend($global_sock, $message & Chr(0))
Endfunc


Func send_pid_table()
	$str = "PID_TABLE"
	For $i=0 To 5
		$str &= " " & $global_game_process_ids[$i]
	Next
	re($str)
Endfunc
