#pragma once

// FORMAT:
// GTA2_FONT styname foreground background size

// fstyle.sty (broken: 0, 1, 13)
#define GTA2_FONT_FSTYLE_GRADIENT_BLACK_NORMAL 2
#define GTA2_FONT_FSTYLE_WHITE_BLACK_NORMAL 3
#define GTA2_FONT_FSTYLE_RED_BLACK_NORMAL 4
#define GTA2_FONT_FSTYLE_WHITE_RED_TINY 5
#define GTA2_FONT_FSTYLE_WHITE_BLACK_TINY 6
#define GTA2_FONT_FSTYLE_WHITE_RED_NORMAL 7
#define GTA2_FONT_FSTYLE_WHITE_RED_SMALL 8
#define GTA2_FONT_FSTYLE_WHITE_BLACK_SMALL 9
#define GTA2_FONT_FSTYLE_BLUE_RED_HUGE 10
#define GTA2_FONT_FSTYLE_RED_BLUE_HUGE 11
#define GTA2_FONT_FSTYLE_WHITE_BLACK_HUGE 12
