#pragma once

#define GTA2_SPRITE_CIRCLE 4
#define GTA2_SPRITE_ARROW_LEFT_RED 39
#define GTA2_SPRITE_ARROW_RIGHT_RED 40
#define GTA2_SPRITE_ARROW_LEFT_WHITE 42
#define GTA2_SPRITE_ARROW_RIGHT_WHITE 43
