#pragma once

/*
        Currently, we send the two generated bytes directly,
        without any special message format, to the proxy dll.

        In case we ever need to do something else with the
        proxydll, we should use this message format.

        If it tuns out, that we'll never need it, we can
        also remove this file.
*/

#define PDLL_MOVEMENT 0xaa
#define PDLL_ERROR 0xee

typedef struct {
  char id;   // use a PDLL_* constant from above!
  short arg; // 32 bit windows: 2 bytes
} proxydll_msg_t;
